apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: activemq-artemis-operator.v0.9.1
  namespace: placeholder
  annotations:
    categories: "Streaming & Messaging"
    certified: "false"
    description: ActiveMQ Artemis Operator provides the ability to deploy and manage stateful ActiveMQ Artemis broker clusters
    containerImage: quay.io/hgao/operator:v0.9.1
    createdAt: 2020-03-09T08:16:32Z
    capabilities: Basic Install
    repository: https://github.com/rh-messaging/activemq-artemis-operator
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemis",
          "metadata": {
              "name": "ex-aao"
          },
          "spec": {
              "deploymentPlan": {
                  "size": 1,
                  "image": "quay.io/hgao/amq-openshift-image:amq743LTS"
              }
          }
      },
      {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
              "name": "ex-aaoaddress"
          },
          "spec": {
              "addressName": "myAddress0",
              "queueName": "myQueue0",
              "routingType": "anycast"
          }
      },
      {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisScaledown",
          "metadata": {
              "name": "ex-aaoscaledown"
          },
          "spec": {
              "localOnly": "true"
          }
      }]
labels:
  operator-activemqartemis: "true"
spec:
  displayName: ActiveMQ Artemis Hwd
  description: Hwd ActiveMQ Artemis Operator provides the ability to deploy and manage stateful ActiveMQ Artemis broker clusters
  keywords:
    - activemqartemis
    - operator
  version: 0.9.1
  maturity: alpha
  maintainers:
    - name: Red Hat, Inc.
      email: rkieley@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-amq/
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_amq/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAACXLAAAlywEaR2RmAAAER0lEQVRYhb2XS0xcVRyHv3PmzstSGLCF4kyAIKDioiXTxgjadqkkXZhWRdOoSzdNExdNNepG07rpwrSJK+PCND6CYUGsVtJFiTYaMjSmgSkS24YZ3hZwmHuZuTP3HhfM4ADz6hT9rc7jf873u+d9BWXqZgs+j6IXxRHgEIIAiloABMsoosAIgusJwZWue6yU068oFRD204HGWRSvAo+U6dcAvsXi/FPT/FGRgUgAb9zBxyhOAc4ywVuVQnBRT/HBwRmMsg2MB2gXkgHg6QrBWzWmbF7qjDJZ0sBYM10SrqLYu0PwLGnRULwYnCJU0MB4gHbh4JcdhwOGDbrNslPR8+ws4Wy5zCYiAbxCMvAfwgFqU4KBqw3sytZp2URmwRWcc1HfzpMj26awLA37N2Wf8Dr4BDgFmREI++nIrPaCcjR3VAQvoLeH99G5YQAH71L5VqtEGpL3AOTNFnzAK/8jPKvjv/l5VHoUvZRxwtnRuzttwJOEYxqKo+VE27PjhJuLxxg2BCPr6V/f6MO89nXReKk4ogEHcwu9J8/gamtfz1jpgo1ThoGVc4zEhn5AHx1ah7/5Gua1r4q7BWwIaplbbUN1L/ex+0BX0YYJXWdVj5PQDaRD4nR7WE2ZMDrEsB9MSsMBJDRpG1dqjtZWYywsLOByezBNk+bW1hx4nFXdQFkW05EI7qoq6hsaygJulQ3VWr4Kz64qHvO7EA6Jsv8dniwcIRBSUlNXi+ZyI6XM101Z0oAloD5bsDY5gXS7cDf60Xw+bNNEH7tF2jTR43GUWJ/3tAJvpk1yfg5zauqB4RJiItzEKLBt0rXnTtD06WcIh4M/D9Rtqss52x9WtzRgJJ+B9M/9TJ2Gxg8/yjhy4+07jSklDgXVhbq0LFLJBNmL1jZ0koOf5w2VEBLhZl5HcblQf8JVhTLjaId6aev/vvj3KEVseRkjmUAgsCwLaZpMPv94fgOCt2RCcAXyP5cAlBkHIJH5otloBD0W4/eREcxkcjN8ZZmkZXF/8S9WF+aI3r1TzG5CCgZl1z1WEHxTLNKwwchsBl+ND4/XS1NLC06nMwe+QjJtAeByOtHcHrxeb4EeAfiuO8qSBqAszgvJSfLciNkF51xZwpifQyAwDQMPkFhcBED/e4VEKgWAtrsa3549KNvCadskF+bzwdPYnIOcJ1m4mQso3skHfxA1fvEj1fv3M3v5S2IXzhQKu3R4JudBAlBl8T4w9jBwAJVOl4JPrFmczWY2PUrHArRJBzcMi72V7nPZGsS+EypUvaRBT/cMt/MaAAg1EdTT/ATUba17SC05bF7omWMkt3DbIR6cIqRBDzCxg/AJDXq2wvMaAOie4XaNRVDCRaDwo6C00sClGotg7rDnquTP6fA+OjMPyOOAp0xwEujH5tzhOcaLBZY0kNWNAHW24hiKozYEJTTZmStBQsyGKQkhW3DdDYPPTHO/nH7/AQDFo5Dow5MRAAAAAElFTkSuQmCC
      mediatype: "image/png"
  labels:
    alm-owner-amq-broker: activemq-artemis-operator
    operated-by: activemq-artemis-operator.v0.9.1
  selector:
    matchLabels:
      ActiveMQArtemis: ex-aao
      application: ex-aao-app
      operated-by: activemq-artemis-operator.v0.9.1
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - name: activemqartemises.broker.amq.io
        version: v2alpha1
        versions:
          - name: v2alpha1
            served: true
            storage: true
          - name: v1alpha1
            served: false
            storage: false
        kind: ActiveMQArtemis
        description: An instance of Active MQ Artemis
        displayName: ActiveMQ Artemis
        resources:
          - kind: Service
            version: v1
          - kind: Route
            version: v1
          - kind: StatefulSet
            version: v1
          - kind: Secret
            version: v1
        specDescriptors:
          - description: User name for standard broker user. It is required for connecting to the broker and the web console. If left empty, it will be generated.
            displayName: AdminUser
            path: adminUser
          - description: Password for standard broker user. It is required for connecting to the broker and the web console. If left empty, it will be generated.
            displayName: AdminPassword
            path: adminPassword
          - description: The number of broker pods to deploy
            displayName: Size
            path: size
          - description: The image used for the broker deployment
            displayName: Image
            path: image
          - description: If true require user password login credentials for broker protocol ports
            displayName: RequireLogin
            path: requireLogin
          - description: If true use persistent volume via persistent volume claim for journal storage
            displayName: PersistenceEnabled
            path: persistenceEnabled
          - description: If aio use ASYNCIO, if nio use NIO for journal IO
            displayName: JournalType
            path: journalType
          - description: If true migrate messages on scaledown
            displayName: MessageMigration
            path: messageMigration
      - name: activemqartemisaddresses.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisAddress
        description: Adding and removing addresses via custom resource definitions
        displayName: ActiveMQ Artemis Address
        specDescriptors:
          - description: The Queue Name
            displayName: Queue Name
            path: queueName
          - description: The Address Name
            displayName: Address Name
            path: addressName
          - description: The Routing Type
            displayName: Routing Type
            path: routingType
      - name: activemqartemisscaledowns.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisScaledown
        description: Provides message migration on clustered broker scaledown
        displayName: ActiveMQ Artemis Scaledown
        specDescriptors:
          - description: Triggered by main ActiveMQArtemis CRD messageMigration entry
            displayName: LocalOnly
            path: localOnly
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: activemq-artemis-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - routes
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - broker.amq.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - "route.openshift.io"
              resources:
                - routes
                - routes/custom-host
                - routes/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete

      deployments:
        - name: activemq-artemis-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: activemq-artemis-operator
            template:
              metadata:
                labels:
                  name: activemq-artemis-operator
              spec:
                serviceAccountName: activemq-artemis-operator
                containers:
                  - name: activemq-artemis-operator
                    image: quay.io/hgao/operator:v0.9.1
                    command:
                      -  /home/activemq-artemis-operator/bin/entrypoint
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "activemq-artemis-operator"
